### ISSUE TITLE
Build a different docker-compose.override.yml file for OS X

### ISSUE THREAD

**Issue by mRoca** [crf-devs/resop#149]
Dans le Makefile, un `make build` sur un mac doit générer un fichier `docker-compose.yml.override.yml` ressemblant à :

```
version: "3.7"

volumes:
  postgres-data: ~
services:
  fpm:
    volumes:
      - ./:/srv:cached

  tools:
    volumes:
      - ./:/srv:cached

  node:
    volumes:
      - ./:/srv:cached

  postgres:
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
```

Et sur un linux :

```
version: "3.7"

volumes:
  postgres-data: ~

services:
  postgres:
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
```

Le mieux serait de conserver un unique fichier `docker-compose.yml.override.yml.dist` et de charger certaines parties en fonction de l'OS
