### ISSUE TITLE
Automatically add dependant skills

### ISSUE THREAD

**Issue by mRoca** [crf-devs/resop#280]
Si un utilisateur possède certaines compétences, d'autres doivent lui être automatiquement attribuées:

```yaml
        ci_bspp: ci_samu
        ci_samu: ci
        ch_vpsp: pse2, ch_vl
        ci: pse2
        pse2: pse1
        pse1: psc1
        ch_vl: benevole
        infirmier: benevole
        ce_maraude: solidar
        solidar: maraudeur
        maraudeur: benevole
        tsa_coreg: pse2
        logisticien: benevole
        resp_perm_soc: benevole
        anim_fle: benevole
        psc1: benevole
        benevole: ~
```

=> remplacer le skill existant `"nouveau"` par `"benevole"`
=> Faire les migrations pour rendre cela rétroactif
=> dans le planning, ne pas afficher les compétences héritées

**Comment by mRoca** [comment]
Un exemple du nouveau format du parameter :

```
        ci_bspp:
            label: CI BSPP
            includes: [ci_samu]
        ci_samu:
            label: CI SAMU
            includes: [ci]
        ch_vpsp:
            label: Chauffeur VPSP
            includes: [pse2, ch_vl]
```
