### ISSUE TITLE
Store user skills in parent organization

### ISSUE THREAD

**Issue by mRoca** [crf-devs/resop#286]
Il faudrait faire passer les confs des skills dans les organisations parentes et virer les 3 paramètres du services.yml:

```yaml
    app.most_important_skills_limit: ~
    app.most_important_skills_to_display: ~
    app.available_skills: ~
```
